Repository openmfp/golang-commons, pull requests merged in 2025-04, with the labels that each got.

#211 feat(controller): add read-only mode to LifecycleManager
  controller/lifecycle/lifecycle.go
Labels: fix, feature

#212 feat: add CommonServiceConfig and general config handling based on viper
  config/config.go
  config/config_test.go
  go.mod
Labels: chore, fix, feature

#215 fix(config): rename leader election flag to 'leader-elect'
  config/config.go
Labels: fix

#216 feat(config): update configuration handling to use cobra commands
  config/config.go
  config/config_test.go
  go.mod
  go.sum
Labels: chore, fix, feature

#219 feat(config): enhance configuration structure with new metrics and local execution flags
  config/config.go
Labels: fix, feature

#221 fix: allow configuring kubeconfig flag
  config/config.go
Labels: fix
